name: pre-commit
description: run pre-commit checks
inputs:
  config-path:
    description: Optional, specify an alternative path to a .pre-commit-config.yaml file
    required: false
    default: '.pre-commit-config.yaml'
  extra-args:
    description: extra arguments passed to pre-commit run command
    required: false
    default: ''
  ignore-failure:
    description: Optional, do not fail the gh-action in case of pre-commit check failure
    required: false
    default: 'false'
outputs:
  status:
    description: Provide the exit code returned by pre-commit run command
    value: ${{ steps.exec-pre-commit.outputs.status }}
  logs:
    description: Logs from the pre-commit run command
    value: ${{ steps.exec-pre-commit.outputs.logs }}

runs:
  using: composite
  steps:
    - name: Validate inputs and export
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        EXTRA_ARGS="${{ inputs.extra-args }}"
        echo "CONFIG_PATH=$CONFIG_PATH" >> "$GITHUB_ENV"
        echo "EXTRA_ARGS=$EXTRA_ARGS"   >> "$GITHUB_ENV"
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Fetch origin
      run: git fetch origin # avoid unknown revision or path not in the working tree when
      # using --from-ref --to-ref feature of pre-commit
      shell: bash
    - id: setup_python
      name: Setup python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13'
    - name: Setup pre-commit
      run: |
        python -m pip install --upgrade pip
        python -m pip install --quiet pre-commit==3.7.1
      shell: bash
    - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: restore-cache
      with:
        key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles(env.CONFIG_PATH) }}
        path: ~/.cache/pre-commit
    - name: Check existence of .pre-commit-config.yaml file
      run: |
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "Could not find any pre-commit configuration at the provided location: '$CONFIG_PATH'"
          exit 1
        fi
      shell: bash
    - id: setup-pre-commit-hooks
      if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Install pre-commit dependencies
      run: |
        pre-commit install-hooks --config="$CONFIG_PATH"
      shell: bash
    - uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: steps.restore-cache.outputs.cache-hit != 'true' &&
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      with:
        key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles(env.CONFIG_PATH) }}
        path: ~/.cache/pre-commit
    - id: exec-pre-commit
      name: Execute pre-commit
      run: |
        set +e
        OUTPUT=$(pre-commit run --config="$CONFIG_PATH" --show-diff-on-failure --color=always $EXTRA_ARGS)
        STATUS=$?
        echo "status=$(echo $STATUS)" >> "$GITHUB_OUTPUT"
        # Securely expose log a random delimiter
        DELIM="DELIM_$(openssl rand -hex 16)"
        while echo "$OUTPUT" | grep -q "$DELIM"; do
          DELIM="DELIM_$(openssl rand -hex 16)"
        done
        echo "logs<<$DELIM" >> "$GITHUB_OUTPUT"
        echo "$OUTPUT" >> "$GITHUB_OUTPUT"
        echo "$DELIM" >> "$GITHUB_OUTPUT"
        exit 0
      shell: bash
    - name: Print execution
      run: |
        echo "${{ steps.exec-pre-commit.outputs.logs }}"
        echo "Exit code: ${{ steps.exec-pre-commit.outputs.status }}"
      shell: bash
    - name: Check status and fail if necessary
      if: ${{ inputs.ignore-failure == 'false' && steps.exec-pre-commit.outputs.status != 0 }}
      run: |
        echo "::error ::pre-commit execution detected some issues"
        exit 1
      shell: bash
